%---------------------------------------------------------------------------------------------------
\chapter{Anexos}
\label{chp_opinion}

A continuación, se anexa el informe “INSPECCIÓN ESPECIALIZADA EN SEGURIDAD Y SALUD EN EL TRABAJO INDUSTRIA CEMENTERA” adjunto al Oficio Nro. MDT-MDT-2024-0333-O, de fecha 10 de abril de 2024,suscrito por la Abg. Ivonne Elizabeth Núñez Figueroa, Ministra del Trabajo. Y, ademas, los informes técnicos de las empresas cementeras UCEM, UNACEM Y HOLCIM adjuntos al memorando Nro. IESS-DSGRT-2024-0872-M, de fecha 28 de junio de 2024.